### ISSUE TITLE
[副担当発表]10月副担当発表の準備

### ISSUE THREAD

**Issue by junichi-fukushima** [junichi-fukushima/tech-flow#11]
# 概要
10月副担当発表の準備が完了していること

# 詳細
10月副担当発表の準備が完了していること

# 完了要件
- [x] PBLメンバーと日程がFixしている。 → 日程いつにします？？
- [x] 副担当・卒業生との日程調整が完了している
- [x] 全メンバー担当分の資料作成が完了している
- [x] 小山先生レビューが完了している
- [ ] 服担当への資料送付が完了している

# リンク
- [服担当発表ドライブ](https://drive.google.com/drive/u/1/folders/1j0fOPRd8N8ul6WV35-79fqzVQ-hraCuw)

**Comment by junichi-fukushima** [comment]
@皆さん
土曜日までに、2ページに記載している担当ぶんのスライドを仕上げてきてください

https://docs.google.com/presentation/d/1qApkyW0aQt-sGukANTGRq1JoWgyQ1BU5zL7MvNVCxjI/edit#slide=id.g2edc570a647_0_0

**Comment by kai650** [comment]
新しいスライド
https://docs.google.com/presentation/d/1DYqWR702Ytq8WqHZgO0DGatYkwPMi4GRSgeDJ25HvjY/edit#slide=id.g2550c78dca9_0_0
