### ISSUE TITLE
[PBL関連業務]インタビューの連絡

### ISSUE THREAD

**Issue by kai650** [junichi-fukushima/tech-flow#15]
# 概要
インタビューの連絡（エンジニアだけ募集）

# 完了要件
- [x] 送信内容を書く
- [ ] 送信内容をレビューしてもらう
- [ ] slackで送信する
- [ ] discordで送信する

**Comment by y-tsubuku** [comment]
```
お疲れ様です！小山PBLの徐です。

私たちのPBLでは、「IT技術関連記事リコメンドウェブサービス」を題材に活動しています。
IT技術者の需要調査のため、インタビューを実施したいと思っております。
ご協力いただけるようでしたら、DMを送っていただければ幸いです。

何卒よろしくお願い致します！
```

- インタビュー時間を入れる（30分）
- IT技術関連記事リコメンドウェブサービス
    - テクノロジー関連のキュレーションサービス
- ご協力いただけるようでしたら 👍のリアクションをお願いします。
    - カイさんが自分の投稿に👍を先にリアクション

**Comment by junichi-fukushima** [comment]
* アクション
10/23まで待って、誰も来なかったらPBLメンバー全員で一人一人にアタックしていく。
