### ISSUE TITLE
[要求]インタビュー質問を考える

### ISSUE THREAD

**Issue by kai650** [junichi-fukushima/tech-flow#19]
# 概要
インタビュー質問を考える

# 詳細
タスクの詳細について書く。

# 完了要件
- [x] インタビュー質問を考える
- [ ] インタビュー質問の理由を書く

# リンク
https://2024pblhq.slack.com/archives/C06QY9VCN13/p1729298363449759

**Comment by y-tsubuku** [comment]
https://www.notion.so/2024-koyamapbl/e403fcc5359648f8b69f8b048e889cb0

**Comment by junichi-fukushima** [comment]
@kai650

理由の部分を土曜日or水曜日までに書いてくる
https://www.notion.so/2024-koyamapbl/e403fcc5359648f8b69f8b048e889cb0 @

**Comment by y-tsubuku** [comment]
こちらが最新
https://www.notion.so/2024-koyamapbl/7ccde705671243788088071834853df2
