### ISSUE TITLE
[開発]Next Authの調査

### ISSUE THREAD

**Issue by jun-koyama-h** [junichi-fukushima/tech-flow#21]
# 概要
Next Authの調査

# 詳細
Next Authの調査

# 完了要件
- [ ] 認証プロバイダについて調査
- [ ] 導入方法について調査

# リンク
ワイヤー・参考資料などのリンクを記載しておく

**Comment by y-tsubuku** [comment]
Googleのみの認証だけでよいのでは？と思っている。

**Comment by y-tsubuku** [comment]
Anonymousログインは未対応
