### ISSUE TITLE
[設計]レコメンド機能のアーキテクチャを決める

### ISSUE THREAD

**Issue by junichi-fukushima** [junichi-fukushima/tech-flow#4]
# 概要
- レコメンド機能のアーキテクチャを決める

# 詳細
- レコメンド機能を作るにあたって大枠のアーキテクチャ/構成を決めたい。
- 機能がまだ決まっていないので、詳細までは決め切らなくても良い(変更する場合は別途チケット切る)

# 完了要件
- [x] レコメンド機能のアーキテクチャが決まっていること
- [x] 使用するFW/プログラミング言語がFixしていること
- [x] 使用するクラウドサービスが決まっていること
- [x] レビューが終わっていること

# リンク
- [notion](https://www.notion.so/2024-koyamapbl/tech-flow-8071a4e461664ab8a46c5507416f59ef)

**Comment by y-tsubuku** [comment]
* レコメンド機能のアーキテクチャが決まっていること
  * metarank https://github.com/metarank/metarank をdockerで動かす
* 使用するFW/プログラミング言語がFixしていること
  * 今回、内部的にはscalaだが、あまり関係ない
* 使用するクラウドサービスが決まっていること
  * AWSのECSで構築する。（EC2起動）

**Comment by y-tsubuku** [comment]
現時点のレビューは不要と考える。なぜなら、OSSを使用すると決まったためである
