### ISSUE TITLE
[要求/要件]レコメンド機能の要求・要件を提案できるようにする

### ISSUE THREAD

**Issue by y-tsubuku** [junichi-fukushima/tech-flow#6]
# 概要
レコメンド機能の要求・要件を提案できるようにする

# 詳細
レコメンド機能の要求・要件の叩きを作成し、PBLメンバーに提案できるようにする

# 完了要件
- [x] レコメンド機能の要求・要件の叩きが完了している
- [x] 各サイトから取得できる情報が一覧化されていること（現在はソースが確定していないので、ある程度の決めで一覧化する。）
- [x] 方針が決まっていること

# リンク
[ワイヤー・参考資料などのリンクを記載しておく](https://docs.google.com/spreadsheets/d/155nc4Wu7NXVLMKXLMqCQahpgcdRng_H_izJ9Dbss0iw/edit?gid=1586589373#gid=1586589373)

**Comment by y-tsubuku** [comment]
https://techblog-matome.okdyy75.com/

**Comment by y-tsubuku** [comment]
https://paiza.hatenablog.com/entry/2024/10/16/190000
https://developer.hatenastaff.com/entry/2024/10/16/180559
https://moneyforward-dev.jp/entry/2024/10/16/160000
https://tech.toreta.in/entry/2024/10/16/%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88%E3%82%BB%E3%83%83%E3%83%882024%E7%A7%8B
https://tech.every.tv/entry/2024/10/16/113616?utm_source=feed
https://techlife.cookpad.com/entry/2024/10/16/101605
https://creators-note.chatwork.com/entry/2024/10/16/100000
https://tech.enechange.co.jp/entry/2024/10/15/235502
https://blog.cybozu.io/entry/2024/10/16/080000
https://developers.cyberagent.co.jp/blog/archives/50206/
https://tech.classi.jp/entry/2024/10/15/180000?utm_source=feed
https://tech.mobilefactory.jp/entry/2024/10/15/160000
https://tech.uzabase.com/entry/2024/10/15/132842
https://techblog.zozo.com/entry/zozometry-improve-performance
https://buildersbox.corp-sansan.com/entry/2024/10/16/110000
https://knowledge.sakura.ad.jp/38975/
https://engineer.crowdworks.jp/entry/2024/10/17/092546
https://techblog-matome.okdyy75.com/blog/paiza/
https://hackerslab.aktsk.jp/2024/10/08/133156
https://dev.classmethod.jp/articles/amazon-fsx-for-netapp-ontap-smb-encryption-performance-comparison/
https://made.livesense.co.jp/entry/2024/10/18/080000
https://zenn.dev/coconala/articles/185a41e3e47bfe
https://www.wantedly.com/companies/wantedly/post_articles/931210#_=_
https://tech.smarthr.jp/entry/qa_series_article_vol2
https://tech.medpeer.co.jp/entry/2024/10/17/175000
https://techracho.bpsinc.jp/hachi8833/2024_10_17/145669
https://nulab.com/ja/blog/nulab/revision-of-terms-of-use-2024/
https://techblog.raksul.com/entry/2024/10/17/113948
https://engineering.dena.com/output/slide/2017/
https://techblog.lycorp.co.jp/ja/20241017a
https://engineering.mercari.com/blog/

**Comment by y-tsubuku** [comment]
https://www.notion.so/2024-koyamapbl/12311557bb6e8051b0b3e8828ba7cac4

**Comment by junichi-fukushima** [comment]
https://docs.google.com/spreadsheets/d/155nc4Wu7NXVLMKXLMqCQahpgcdRng_H_izJ9Dbss0iw/edit?gid=311928125#gid=311928125


今のままだと、技術テックブログまとめサイトや既存キュレーションサービスの焼き直しになりかねない
解決案の方向性を改めて検討した方が良さそう

**Comment by y-tsubuku** [comment]
下記に叩きを作成した。
https://www.notion.so/2024-koyamapbl/804d7d2c7dd54b828df838f8e657ccb7
